---
title: "gather"
author: "Eleanor Fitzgibbons"
date: "11/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(gt)
library(rstanarm)
library(ggplot2)

# This Rmd includes all of the code that I used in my final app. I copy and
# pasted my graphs from here to the shiny app, and then I changed the parts that
# needed to be filtered to different inputs once in the app.

```


```{r}
SCDB_2020_01_justiceCentered_Citation <- 
  read_csv("final-app/SCDB_2020_01_justiceCentered_Citation.csv",
           col_types = cols(.default = col_double(),
                            caseId = col_character(),
                            docketId = col_character(),
                            caseIssuesId = col_character(),
                            voteId = col_character(),
                            dateDecision = col_character(),
                            usCite = col_character(),
                            sctCite = col_character(),
                            ledCite = col_character(),
                            lexisCite = col_character(),
                            chief = col_character(),
                            caseName = col_character(),
                            dateArgument = col_character(),
                            dateRearg = col_character(),
                            lawMinor = col_character(),
                            justiceName = col_character()))

Citation_Data <- SCDB_2020_01_justiceCentered_Citation %>% 
  select(sctCite, caseId, caseName, dateDecision, dateArgument, chief, issue, 
         issueArea, decisionDirection, justiceName, vote, opinion, direction, 
         majority) %>% 
  mutate(date = str_sub(dateDecision, -4)) %>% 

  # I originally did == instead of %in%  
  
  mutate(president = case_when(justiceName %in% c("RHJackson", "WODouglas", 
                                                  "FFrankfurter", "SFReed", 
                                                  "HLBlack", "WBRutledge",
                                                  "FMurphy") ~ "Roosevelt",
                               justiceName %in% c("HHBurton", "FMVinson", 
                                                  "TCClark", 
                                                  "SMinton") ~ "Truman",
                               justiceName %in% c("EWarren", "JHarlan2", 
                                                  "WJBrennan", "CEWhittaker", 
                                                  "PStewart") ~ "Eisenhower",
                               justiceName %in% c("BRWhite", 
                                                  "AJGoldberg") ~ "Kennedy",
                               justiceName %in% c("AFortas", 
                                                  "TMarshall") ~ "Johnson",
                               justiceName %in% c("WEBurger", "HABlackmun", 
                                                  "LFPowell",
                                                  "WHRehnquist") ~ "Nixon",
                               justiceName %in% c("JPStevens") ~ "Ford",
                               justiceName %in% c("SDOConnor", "AScalia", 
                                                "AMKennedy") ~ "Reagan",
                               justiceName %in% c("DHSouter", 
                                                  "CThomas") ~ "HW Bush",
                               justiceName %in% c("RBGinsburg", 
                                                  "SGBreyer") ~ "Clinton",
                               justiceName %in% c("JGRoberts", 
                                                  "SAAlito") ~ "Bush",
                               justiceName %in% c("SSotomayor", 
                                                  "EKagan") ~ "Obama",
                               justiceName %in% c("NMGorsuch", 
                                                  "BMKavanaugh") ~ "Trump")) %>%
  group_by(justiceName) %>% 
  mutate(direction_mean = mean(direction, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(chiefYES = case_when(chief == str_sub(justiceName, 3, -1) ~ "yes",
                              chief == str_sub(justiceName, 2, -1) ~ "yes",
                              TRUE ~ "no")) %>% 
  mutate(issueArea_name = case_when(issueArea == 1 ~ "Criminal Procedure",
                                    issueArea == 2 ~ "Civil Rights",
                                    issueArea == 3 ~ "First Amendment",
                                    issueArea == 4 ~ "Due Process",
                                    issueArea == 5 ~ "Privacy",
                                    issueArea == 6 ~ "Attorneys",
                                    issueArea == 7 ~ "Unions",
                                    issueArea == 8 ~ "Economic Activity",
                                    issueArea == 9 ~ "Judicial Power",
                                    issueArea == 10 ~ "Federalism",
                                    issueArea == 11 ~ "Interstate Relations",
                                    issueArea == 12 ~ "Federal Taxation",
                                    issueArea == 13 ~ "Miscellaneous",
                                    issueArea == 14 ~ "Private Action")) %>% 
  
  # Some of these lines are over 80 characters because I can't break them up.
  
  mutate(justice_fullnames = case_when(justiceName == "HHBurton" ~ "Harold Hitz Burton",
                                       justiceName == "RHJackson" ~ "Robert H. Jackson",
                                       justiceName == "WODouglas" ~ "William O. Douglas",
                                       justiceName == "FFrankfurter" ~ "Felix Frankfurter",
                                       justiceName == "SFReed" ~ "Stanley Forman Reed",
                                       justiceName == "HLBlack" ~ "Hugo Black",
                                       justiceName == "WBRutledge" ~ "Wiley Blount Rutledge",
                                       justiceName == "FMurphy" ~ "Frank Murphy",
                                       justiceName == "FMVinson" ~ "Fred M. Vinson",
                                       justiceName == "TCClark" ~ "Tom C. Clark",
                                       justiceName == "SMinton" ~ "Sherman Minton",
                                       justiceName == "EWarren" ~ "Earl Warren",
                                       justiceName == "JHarlan2" ~ "John Marshall Harlan II",
                                       justiceName == "WJBrennan" ~ "William J. Brennan Jr.",
                                       justiceName == "CEWhittaker" ~ "Charles Evans Whittaker",
                                       justiceName == "PStewart" ~ "Potter Stewart",
                                       justiceName == "BRWhite" ~ "Byron White",
                                       justiceName == "AJGoldberg" ~ "Arthur Goldberg",
                                       justiceName == "AFortas" ~ "Abe Fortas",
                                       justiceName == "TMarshall" ~ "Thurgood Marshall",
                                       justiceName == "WEBurger" ~ "Warren E. Burger",
                                       justiceName == "HABlackmun" ~ "Harry Blackmun",
                                       justiceName == "LFPowell" ~ "Lewis F. Powell Jr.",
                                       justiceName == "WHRehnquist" ~ "William Rehnquist",
                                       justiceName == "JPStevens" ~ "John Paul Stevens",
                                       justiceName == "SDOConnor" ~ "Sandra Day O'Connor",
                                       justiceName == "AScalia" ~ "Antonin Scalia",
                                       justiceName == "AMKennedy" ~ "Anthony Kennedy",
                                       justiceName == "DHSouter" ~ "David Souter",
                                       justiceName == "CThomas" ~ "Clarence Thomas",
                                       justiceName == "RBGinsburg" ~ "Ruth Bader Ginsburg",
                                       justiceName == "SGBreyer" ~ "Stephen Breyer",
                                       justiceName == "JGRoberts" ~ "John Roberts",
                                       justiceName == "SAAlito" ~ "Samuel Alito",
                                       justiceName == "SSotomayor" ~ "Sonia Sotomayor",
                                       justiceName == "EKagan" ~ "Elena Kagan",
                                       justiceName == "NMGorsuch" ~ "Neil Gorsuch",
                                       justiceName == "BMKavanaugh" ~ "Brett Kavanaugh"))

# I was having trouble loading this dataset into my app, so I had to play around
# with the working directory here.

setwd("~/Desktop/projects/gov50-final-project/final-app")
write.csv(Citation_Data, "Citation_Data.csv")

```

```{r}

# For most of these graphs, I specified which justice I wanted to look at using
# the filter argument. However, when I put them in my app, I wanted to make most
# of them interactive, so I had to change the filter arguments in my app to be
# whatever the input is. That's why this code looks slightly different in the
# shiny app.

Citation_Data %>% 
  filter(justiceName == "RBGinsburg") %>% 
  drop_na(direction) %>% 
  ggplot(aes(x = direction)) +
  geom_bar() +
  theme_bw() +
  labs(title = "Ideological Direction Count",
       x = "Direction",
       y = "Count") +
  scale_x_continuous(breaks = c(1, 2),
                     label = c("Conservative", "Liberal"))
```

```{r}

# I put this graph on the first page of my shiny app. My final project focuses
# on the voting records of each justice and their ideological leaning. I thought
# this graph pretty accurately gives a snapshot of the data I'm exploring, as it
# gives the average direction grouped by justice. It also displays the justices
# in order of most to least conservative. I think it's interesting to see all of
# these justices from different time periods on one page like this.

Citation_Data %>% 
  ggplot(aes(x = fct_reorder(justiceName, direction_mean), 
             y = direction_mean)) +
  geom_point(color = "lightblue") +
  labs(title = "Ideological Direction of Supreme Court Justices",
       subtitle = "Average of Ideological Leanings in Cases from 1946-2020",
       x = "Justices",
       y = "Ideological Direction") +
  theme_bw() +
  
  # I had to do this on most of my graphs in order to see each justice's full
  # name.
  
  theme(axis.text.x = element_text(angle = 90))
```

```{r}

# I made this an interactive graph where you can toggle the president in my
# shiny app.

Citation_Data %>% 
  filter(president == "Roosevelt") %>% 
  drop_na(direction) %>% 
  ggplot(aes(x = justice_fullnames, y = direction_mean)) +
  geom_point(color = "navyblue") +
  theme_bw() +
  labs(title = "Average Ideological Direction",
       subtitle = "Of the Justices Appointed by the Selected President",
       x = "Justices",
       y = "Ideological Direction") +
  ylim(c(1, 2)) +
  theme(axis.text.x = element_text(angle = 20, vjust = 0.5))
```

```{r}

# I ended up not including this graph in my shiny app. I was expecting the data
# to show more obvious trends, but it does not. In and of itself, that is not a
# bad thing. The point of my project is to explore the data, so seeing no
# pattern is just as interesting as seeing one. However, I think the different
# issue areas are confusing because some areas don't have data for all of the
# justices. I could keep it this graph in my project, but it doesn't add
# anything to the project, and I think it actually takes away from the rest of
# it.

Citation_Data %>%
  filter(justiceName == "RBGinsburg") %>%
  drop_na(direction) %>%
  distinct(sctCite, .keep_all = TRUE) %>%
  filter(issueArea_name %in% c("Civil Rights", "Economic Activity")) %>%
  ggplot(aes(x = sctCite, y = direction)) +
  
  # I used geom_jitter instead of geom_point so that you can actually see the
  # different points. I realized it doesn't matter were exactly the points are
  # so long as they are in the area of liberal or in the area of conservative
  # because the only options for y are 1 or 2, meaning there are no values in
  # between. I then added an alpha argument to make it even more clear.
  
  geom_jitter(height = 0.05, alpha = 0.75) +
  facet_wrap( ~issueArea_name, ncol = 4) +
  labs(title = "Ideological Direction by Issue",
       x = "",
       y = "Ideological Direction") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(angle = 90, hjust = 0.5)) +
  scale_y_continuous(breaks = c(1, 2),
                     
                     # I changed these labels to liberal and conservative
                     # because, unlike the other graphs, I did not take the
                     # average ideological direction for each judge, I simply
                     # left the direction as is. Thus, the only y values were 1
                     # or 2, representing conservative or liberal.
                     
                     labels = c("Conservative", "Liberal"))

```

Is the chief justice typically in the majority?
```{r}

# This one isn't an interactive graph, so I put it into my project as is. I am
# fascinated by the dynamics of the Supreme Court, and I always wonder what kind
# of role the chief justice plays, so this was really interesting for me to see.
# There isn't much of a pattern, but the chiefs are in the majority slightly
# more than others.

Citation_Data %>%
  group_by(justiceName) %>% 
  mutate(n_maj = sum(majority == 2, na.rm = TRUE),
         pct_maj = n_maj/sum(majority, na.rm = TRUE),
         .groups = "drop") %>% 
  ggplot(aes(x = justiceName, y = pct_maj, color = chiefYES)) +
  geom_point() +
  labs(title = "Are Chief Justices More Frequently in the Majority?",
       x = "Justice",
       y = "Percent of Time in Majority") +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_color_manual(labels = c("No", "Yes"),
                     values = c("green", "blue"),
                     name = "Chief Justice?")
```


```{r}

# I actually created model_3 in the test.Rmd. It tkok a couple hours to run, so
# I decided to leave it in that Rmd and save it as a new object to use in this
# one.

print(model_3, digits = 3)

# I then saved the model as an RDS object for the same reason. I didn't want my
# shiny app to take hours to run, so I saved it as an object that already ran in
# order to streamline my app.

saveRDS(model_3, file = "justiceissue_model.rds")

# This creates the regression table that you see at the beginning of my model
# page.

tbl_regression(justiceissue_model, intercept = TRUE) %>% 
  as_gt() %>% 
  
  # This line is more than 80 characters because I couldn't split it up easily.
  
  tab_header(title = "Regression of Ideological Leaning by Justice and Issue Area")

# Next, I made a new tibble using this data. In the shiny app, I left the
# justice choices up to the viewer, but I left the issue area as Civil Rights
# regardless. As I mentioned earlier, some issue areas don't have data for each
# justice, so it made less sense to let the viewer choose.

new_obs <- tibble(justice_fullnames = c("Ruth Bader Ginsburg", "Neil Gorsuch"),
                  issueArea_name = "Civil Rights")
pe <- posterior_epred(model_3, 
                      newdata = new_obs) %>% 
  as_tibble() %>%
  rename("Ruth Bader Ginsburg" = `1`,
         "Neil Gorsuch" = `2`) %>% 
  pivot_longer(cols = 1:2, 
               names_to = "Parameter",
               values_to = "Direction")

# Here is the code for my posterior probability distribution. I think this graph
# is really cool actually. You can see which justices would vote similarly and
# which would vote very differently. It's also interesting to see which have a
# larger distribution and which tend to vote the same way more frequently.

pe %>% 
ggplot(aes(Direction, fill = Parameter)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 1000,
                   position = "identity") +
    labs(title = "Posterior Probability Distribution",
         subtitle = "For Ruth Bader Ginsburg and Neil Gorsuch regarding Civil Right Issues",
         x = "Expected Direction of Vote",
         y = "Probability") + 
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
```

```{r}

# This graph explores the ideological leaning over time. Some justices do have a
# bit of a trend, such as RBG in this example, but they are relatively
# consistent over time.

Citation_Data %>% 
  mutate(date = as.numeric(date)) %>% 
  group_by(justice_fullnames, date) %>% 
  mutate(avg_direction_year = mean(direction, na.rm = TRUE)) %>% 
  filter(justice_fullnames == "Ruth Bader Ginsburg") %>% 
  ggplot(aes(x = date, y = avg_direction_year)) +
  geom_point(color = "darkblue") +
  
  # I had trouble with geom_smooth at first because I hadn't mutated the date
  # variable to be numeric. I didn't realize that the trend line wouldn't work
  # on the numbers when they were categorized as characters.
  
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "Average Ideological Direction Over Time",
       x = "Year",
       y = "Average Direction") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  ylim(c(1, 2))
```






