---
title: "Test"
author: "Eleanor Fitzgibbons"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(gt)
library(rstanarm)

# This Rmd is where I tested things I was curious or confused about. I didn't
# end up using this code in my final shiny app. I think of this Rmd as more of a
# piece of scrap paper.

```

```{r}

# I used this data originally, but then I decided that I preferred the data
# organized by Supreme Court Citatino instead of Docket.

SCDB_2020_01_justiceCentered_Docket <- 
  read_csv("final-app/SCDB_2020_01_justiceCentered_Docket.csv",
           col_types = cols(.default = col_double(),
                            caseId = col_character(),
                            docketId = col_character(),
                            caseIssuesId = col_character(),
                            voteId = col_character(),
                            dateDecision = col_character(),
                            usCite = col_character(),
                            sctCite = col_character(),
                            ledCite = col_character(),
                            lexisCite = col_character(),
                            chief = col_character(),
                            caseName = col_character(),
                            dateArgument = col_character(),
                            dateRearg = col_character(),
                            lawMinor = col_character(),
                            justiceName = col_character()))
```

```{r}
Citation_Data %>% 
  distinct(justice_fullnames)
```

```{r}
IssueArea <- tibble(Number = c(1:14),
                    Issue = c("Criminal Procedure", "Civil Rights", 
                              "First Amendment", "Due Process",  "Privacy", 
                              "Attorneys", "Unions", "Economic Activity", 
                              "Judicial Power", "Federalism", 
                              "Interstate Relations", "Federal Taxation", 
                              "Miscellaneous", "Private Action"))
gt_IssueArea <- gt(data = IssueArea) %>% 
  tab_header(title = "Issue Area Code")

# Link to online code book for SCDB: http://supremecourtdatabase.org/documentation.php
```


```{r}
# ggplot(d, aes(.data[[input$x]], .data[[input$y]])) +
#             plot_geom()


model_data <- Citation_Data %>% 
  mutate(outcome = case_when(direction == 1 ~ 1,
                             direction == 2 ~ 0))

# Here's the model I ran originally out of curiosity. I knew the stan_glm would
# take forever, so I quickly ran this to get an idea of what I would see.

model <- glm(outcome ~ chief + justiceName + date,
             data = model_data,
             family = "binomial")
summary(model)
```

```{r}

# I had a problem with my code in this graph once I ran the app. I put the code
# into this Rmd to try to figure it out. I tried just about everything before
# deciding to restart R and my problem was solved.

d %>% 
            filter(justice_fullnames == "Ruth Bader Ginsburg") %>% 
            drop_na(direction) %>% 
            distinct(sctCite, .keep_all = TRUE) %>% 
            filter(issueArea_name %in% c("Economic Activity",
                                         "Criminal Procedure")) %>% 
            ggplot(aes(x = sctCite, y = direction)) +
            geom_jitter(height = 0.05, alpha = 0.75,
                        color = "navyblue") +
            
            # I am getting a warning that says "Faceting variables must have at
            # least one value, but I selected variables using selected=...
            
            facet_wrap( ~issueArea_name) +
            labs(title = "Ideological Direction by Issue",
                 x = "",
                 y = "Ideological Direction") +
            theme_bw() +
            theme(plot.title = element_text(hjust = 0.5),
                  axis.text.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  axis.text.y = element_text(angle = 90, hjust = 0.5)) +
            scale_y_continuous(breaks = c(1, 2),
                               labels = c("Conservative", "Liberal"))
```

Frequency in majority over time?
```{r}

# This idea was cool but I couldn't figure out how to include only the years
# that each justice served on the court...

Citation_Data %>% 
  group_by(justiceName, date) %>% 
  mutate(n_maj_year = sum(majority == 2, na.rm = TRUE)) %>% 
  mutate(pct_maj_year = n_maj_year/sum(majority %in% c(1, 2), na.rm = TRUE)) %>% 
  filter(justiceName %in% c("SSotomayor", "RBGinsburg")) %>% 
  distinct(date, .keep_all = TRUE) %>% 
  ggplot(aes(x = date, y = pct_maj_year, fill = justiceName)) +
  geom_col(position = position_dodge()) +
  facet_wrap( ~justiceName) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(labels = scales::percent_format())
```

A look at each justice's distribution by issue
```{r}

# I wanted to see which justices tend to vote more liberally depending on the
# context... The results were not super interesting and some of the issue areas
# had zero data.

# 11 resulted in nothing and 13 and 14 have very few data points...

Citation_Data %>% 
  filter(issueArea == 2) %>% 
  group_by(justiceName) %>% 
  mutate(direction_mean_issue = mean(direction, na.rm = TRUE)) %>% 
  ungroup() %>% 
  ggplot(aes(x = justiceName, y = direction_mean_issue)) +
  geom_point() +
  labs(title = "Average Ideological Leaning By Issue",
       x = "Justice",
       y = "Average Ideological Direction") +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}

# All of this should actualy be in my gather.Rmd, but it took hours to load this
# model and I didn't want to wait for it to load again. Instead, I just saved it
# as an object here and then worked with the object model_3 in the other Rmd.

model_data <- Citation_Data %>% 
  mutate(outcome = case_when(direction == 1 ~ 1,
                             direction == 2 ~ 0))

model_3 <- stan_glm(data = model_data,
                    outcome ~ justice_fullnames + issueArea_name - 1,
                    family = "binomial",
                    refresh = 0,
                    iter = 10000)

print(model_3, digits = 3)

saveRDS(model_3, file = "justiceissue_model.rds")

tbl_regression(justiceissue_model, intercept = TRUE) %>% 
            as_gt() %>% 
            tab_header(title = "Regression of Ideological Leaning by Justice and Issue Area")
```

```{r}
Citation_Data %>% 
  filter(issueArea == 14) %>% 
  distinct(sctCite, .keep_all = TRUE)
```

```{r, message=FALSE}

# I played around with a couple different models. I originally wanted to look at
# the way each justice might vote with the date variable as a constant in order
# to remove the possibility that time could be confounding the directions. I had
# more trouble interpreting this model, however, and I don't think it was doing
# exactly what I wanted, so I decided to use issueArea as my explanatory
# variable in model_3.

model_edited <- Citation_Data %>% 
  mutate(outcome = case_when(direction == 1 ~ 1,
                             direction == 2 ~ 0)) %>% 
  mutate(date = as.numeric(date))
  
model_2 <- stan_glm(data = model_edited,
                    outcome ~ chief + justice_fullnames + date - 1,
                    family = "binomial",
                    refresh = 0)
print(model_2, digits = 3)
```

```{r}

# Here is scrap work from when my TF and I were trying to figure out why my
# geom_smooth wouldn't work in the graph that looks at justice leaning over
# time. We then realized that my date variable was not numeric!

timeplot <- Citation_Data %>% 
  group_by(justice_fullnames, date) %>% 
  mutate(avg_direction_year = mean(direction, na.rm = TRUE))

fit_lm <- lm(avg_direction_year ~ date,
             data = timeplot)

timeplot$predlm <- predict(fit_lm)
  
ggplot(timeplot, mapping = aes(x = date, y = predlm)) +
  geom_point() 
```
