---
title: "Test"
author: "Eleanor Fitzgibbons"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(gt)
```

```{r}
SCDB_2020_01_justiceCentered_Docket <- 
  read_csv("final-app/SCDB_2020_01_justiceCentered_Docket.csv",
           col_types = cols(.default = col_double(),
                            caseId = col_character(),
                            docketId = col_character(),
                            caseIssuesId = col_character(),
                            voteId = col_character(),
                            dateDecision = col_character(),
                            usCite = col_character(),
                            sctCite = col_character(),
                            ledCite = col_character(),
                            lexisCite = col_character(),
                            chief = col_character(),
                            caseName = col_character(),
                            dateArgument = col_character(),
                            dateRearg = col_character(),
                            lawMinor = col_character(),
                            justiceName = col_character()))
```

```{r}
Citation_Data %>% 
  distinct(justice_fullnames)
```
```{r}
IssueArea <- tibble(Number = c(1:14),
                    Issue = c("Criminal Procedure", "Civil Rights", 
                              "First Amendment", "Due Process",  "Privacy", 
                              "Attorneys", "Unions", "Economic Activity", 
                              "Judicial Power", "Federalism", 
                              "Interstate Relations", "Federal Taxation", 
                              "Miscellaneous", "Private Action"))
gt_IssueArea <- gt(data = IssueArea) %>% 
  tab_header(title = "Issue Area Code")

# Link to online code book for SCDB: http://supremecourtdatabase.org/documentation.php
```


```{r}
# ggplot(d, aes(.data[[input$x]], .data[[input$y]])) +
#             plot_geom()


model_data <- Citation_Data %>% 
  mutate(outcome = case_when(direction == 1 ~ 1,
                             direction == 2 ~ 0))

model <- glm(outcome ~ chief + justiceName + date,
             data = model_data,
             family = "binomial")
summary(model)
```





